apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: curl
  name: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: curl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curl
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while [ 1 -eq 1 ] ; do sleep 10; done
        image: curlimages/curl
        name: curl
      restartPolicy: Always
