name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "*"
  pull_request:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Build
      run: make build

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
# https://github.com/castai/kilo/issues/5
#    - name: Build docs
#      run: |
#        make gen-docs
#        git diff --exit-code

  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Run Unit Tests
      run: make unit

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Run e2e Tests
      run: make e2e

  # https://github.com/castai/kilo/issues/12
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Set up Go
  #    uses: actions/setup-go@v4
  #    with:
  #      go-version: 1.23
  #  - name: Lint Code
  #    run: make lint

